--- #YAML:1.0
name:               POE-Component-Server-MySQL
version:            0.01
abstract:           A MySQL POE Server
author:
    - Eriam Schaffter <eriam@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Inspector:     0
    DBI:                  0
    Module::Find:         0
    Moose:                0
    MooseX::MethodAttributes:  0
    POE:                  0
    Test::More:           0
    Time::HiRes:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
